# Generated by Django 4.2.8 on 2026-03-29 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlazaInternado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='False = registro eliminado (soft delete). Nunca eliminar físicamente.', verbose_name='Activo')),
                ('date_create', models.DateTimeField(blank=True, help_text='Se asigna automáticamente. No modificar manualmente.', null=True, verbose_name='Fecha de creación')),
                ('ip_create', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de creación')),
                ('date_modification', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificación')),
                ('ip_modification', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modificación')),
                ('date_delete', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('ip_delete', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de eliminación')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Plaza')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución de Salud')),
                ('area', models.CharField(choices=[('clinica', 'Clínica'), ('cirugia', 'Cirugía'), ('pediatria', 'Pediatría'), ('ginecologia', 'Ginecología'), ('emergencias', 'Emergencias'), ('medicina_interna', 'Medicina Interna'), ('otro', 'Otro')], max_length=30, verbose_name='Área')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('cancelada', 'Cancelada')], default='disponible', max_length=15)),
                ('periodo', models.CharField(max_length=20, verbose_name='Período Académico')),
                ('user_create', models.ForeignKey(blank=True, help_text='Se asigna automáticamente. No modificar manualmente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('user_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Plaza de Internado',
                'verbose_name_plural': 'Plazas de Internado',
                'ordering': ['institucion', 'area'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='False = registro eliminado (soft delete). Nunca eliminar físicamente.', verbose_name='Activo')),
                ('date_create', models.DateTimeField(blank=True, help_text='Se asigna automáticamente. No modificar manualmente.', null=True, verbose_name='Fecha de creación')),
                ('ip_create', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de creación')),
                ('date_modification', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificación')),
                ('ip_modification', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modificación')),
                ('date_delete', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('ip_delete', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de eliminación')),
                ('posicion_ranking', models.PositiveIntegerField(verbose_name='Posición en el Ranking')),
                ('puntaje_xgboost', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Puntaje XGBoost')),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('aceptada', 'Aceptada por el Estudiante'), ('rechazada', 'Rechazada por el Estudiante'), ('cancelada', 'Cancelada por Institución')], default='asignada', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='estudiantes.estudiante')),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='plazas.plazainternado')),
                ('user_create', models.ForeignKey(blank=True, help_text='Se asigna automáticamente. No modificar manualmente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('user_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Asignación de Plaza',
                'verbose_name_plural': 'Asignaciones de Plaza',
                'ordering': ['posicion_ranking'],
                'unique_together': {('estudiante', 'plaza')},
            },
        ),
    ]
