# Generated by Django 4.2.8 on 2026-04-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApelacionInternado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('documentos_url', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PRESENTADA', 'Presentada'), ('EN_REVISION', 'En Revisión'), ('RESUELTA', 'Resuelta'), ('DENEGADA', 'Denegada')], default='PRESENTADA', max_length=20)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('resuelto_por', models.UUIDField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'practicas"."apelacion_internado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionInternado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada'), ('REASIGNADA', 'Reasignada'), ('CANCELADA', 'Cancelada')], default='ASIGNADA', max_length=20)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=300, null=True)),
                ('asignado_por', models.UUIDField(blank=True, null=True)),
                ('es_automatica', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'practicas"."asignacion_internado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstitucionReceptora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('id_parroquia', models.SmallIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=120, null=True)),
                ('contacto_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'practicas"."institucion_receptora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogPrediccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entidad_tipo', models.CharField(default='estudiante', max_length=60)),
                ('entidad_id', models.UUIDField()),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('confianza', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('tiempo_ms', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ia"."log_prediccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModalidadPractica',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'practicas"."modalidad_practica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CLASIFICACION', 'Clasificación'), ('REGRESION', 'Regresión'), ('RECOMENDACION', 'Recomendación'), ('NLP', 'NLP'), ('GENERATIVO', 'Generativo')], default='REGRESION', max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sistema_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_despliegue', models.DateField(blank=True, null=True)),
                ('metricas', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ia"."modelo_ia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlazaPractica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plaza', models.CharField(max_length=200)),
                ('cupo_total', models.SmallIntegerField(default=1)),
                ('cupo_disponible', models.SmallIntegerField(default=1)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requisitos_especificos', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'practicas"."plaza_practica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankingInternado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_total', models.DecimalField(decimal_places=4, max_digits=6)),
                ('detalle_puntaje', models.JSONField(blank=True, null=True)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('generado_por_ia', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'practicas"."ranking_internado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInstitucionReceptora',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'practicas"."tipo_institucion_receptora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificacionRequisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_requisito', models.IntegerField()),
                ('cumple', models.BooleanField()),
                ('evidencia_url', models.URLField(blank=True, max_length=500, null=True)),
                ('verificado_por', models.UUIDField(blank=True, null=True)),
                ('verificado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo_requisito', models.CharField(blank=True, choices=[('MODULO_APROBADO', 'Módulo Aprobado'), ('CALIFICACIONES', 'Calificaciones Cerradas'), ('INGLES', 'Módulos de Inglés'), ('OTRO', 'Otro')], max_length=30, null=True)),
            ],
            options={
                'db_table': 'practicas"."verificacion_requisito',
                'managed': False,
            },
        ),
    ]
