# Generated by Django 4.2.8 on 2026-04-06 03:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(choices=[('HIJO', 'Hijo/a'), ('PADRE', 'Padre'), ('MADRE', 'Madre'), ('CONYUGUE', 'Cónyuge'), ('HERMANO', 'Hermano/a'), ('OTRO', 'Otro')], max_length=30)),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
                ('es_dependiente', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estudiantil"."carga_familiar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'academico"."carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('nivel_actual', models.SmallIntegerField(blank=True, null=True)),
                ('modalidad', models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HIBRIDA', 'Híbrida')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('RETIRADO', 'Retirado'), ('GRADUADO', 'Graduado'), ('BECA', 'Con Beca')], default='ACTIVO', max_length=20)),
                ('beca', models.BooleanField(default=False)),
                ('tipo_beca', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'estudiantil"."estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(blank=True, choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=10, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'core"."parroquia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('en_curso', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academico"."periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=60)),
                ('segundo_nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('primer_apellido', models.CharField(max_length=60)),
                ('segundo_apellido', models.CharField(blank=True, max_length=60, null=True)),
                ('email_personal', models.EmailField(blank=True, max_length=120, null=True)),
                ('email_institucional', models.EmailField(blank=True, max_length=120, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core"."persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacionEconomica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_miembros_hogar', models.SmallIntegerField(blank=True, null=True)),
                ('nivel_pobreza', models.CharField(blank=True, choices=[('EXTREMA', 'Pobreza Extrema'), ('BAJA', 'Nivel Bajo'), ('MEDIA', 'Nivel Medio'), ('ALTA', 'Nivel Alto')], max_length=20, null=True)),
                ('tiene_bono_desarrollo', models.BooleanField(default=False)),
                ('tiene_discapacidad', models.BooleanField(default=False)),
                ('porcentaje_discapacidad', models.SmallIntegerField(blank=True, null=True)),
                ('trabaja', models.BooleanField(default=False)),
                ('horas_trabajo_semana', models.SmallIntegerField(blank=True, null=True)),
                ('actualizado_en', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'estudiantil"."situacion_economica',
                'managed': False,
            },
        ),
    ]
