# Generated by Django 4.2.8 on 2026-03-29 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='False = registro eliminado (soft delete). Nunca eliminar físicamente.', verbose_name='Activo')),
                ('date_create', models.DateTimeField(blank=True, help_text='Se asigna automáticamente. No modificar manualmente.', null=True, verbose_name='Fecha de creación')),
                ('ip_create', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de creación')),
                ('date_modification', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de modificación')),
                ('ip_modification', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de modificación')),
                ('date_delete', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('ip_delete', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de eliminación')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Unión Libre'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20)),
                ('cargas_familiares', models.PositiveIntegerField(default=0)),
                ('ubicacion_geografica', models.CharField(choices=[('urbana', 'Urbana'), ('rural', 'Rural'), ('periurbana', 'Periurbana')], max_length=20)),
                ('situacion_economica', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media-Baja'), (3, 'Media'), (4, 'Media-Alta'), (5, 'Alta')])),
                ('calificaciones', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nivel_academico', models.PositiveIntegerField()),
                ('modulos_ingles_aprobados', models.BooleanField(default=False)),
                ('calificaciones_cerradas', models.BooleanField(default=False)),
                ('user_create', models.ForeignKey(blank=True, help_text='Se asigna automáticamente. No modificar manualmente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user_delete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('user_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['-date_create'],
            },
        ),
    ]
